server:
  # 端口
  port: 8089
spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/farm?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 60000
      connection-timeout: 60000
      validation-timeout: 3000
      login-timeout: 5
      max-lifetime: 60000
      read-only: false
  servlet:
    multipart:
      #单文件大小限制
      max-file-size: 10MB
      #总上传大小限制
      max-request-size: 100MB

  redis:
    host: 127.0.0.1
    port: 6379
    password: qwe123

mybatis-plus:
  global-config:
    db-config:
      id-type: AUTO
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false

upload:
  # 上传的图片保存路径
  path: E://upload//avatar//
